export const theme = {
    colors: {
        background: '#f5f7fa',
        cardBg: '#ffffff',
        textPrimary: '#1a1a1a',
        textSecondary: '#666666',
        textTertiary: '#888888',
        textMuted: '#999999',
        textLight: '#aaaaaa',
        border: '#e8e8e8',
        borderLight: '#eeeeee',
        borderMedium: '#e0e0e0',
        borderDark: '#dddddd',
        hoverBg: '#f6f6f6',
        activeBg: '#f5f5f5',
        inputBg: '#ffffff',
        buttonPrimaryBg: '#1a1a1a',
        buttonPrimaryText: '#ffffff',
        buttonPrimaryBorder: '#1a1a1a',
        buttonGhostBg: '#ffffff',
        buttonGhostText: '#1a1a1a',
        buttonGhostBorder: '#dddddd',
        viewerEmptyBg: '#fafafa',
        viewerEmptyBorder: '#e0e0e0',
        adminPageBg: '#f5f7fa',
    },
    // --- UI-1 design tokens (typography / radius / shadow / spacing) ---
    // Single modern system sans stack — no web-font download (offline-safe for
    // the workshop). `fonts.mono` is available for technical/numeric contexts.
    fonts: {
        sans: "system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
        mono: "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace",
    },
    // Existing radii in the app are 4 / 6 / 8 / 10; keep the same scale, named.
    radius: {
        sm: 4,
        md: 6,
        lg: 8,
        xl: 10,
        pill: '50%',
    },
    // Subtle, minimal — matches the existing inline shadows already in use.
    shadow: {
        none: 'none',
        sm: '0 2px 5px rgba(0,0,0,0.1)',
        md: '0 6px 24px rgba(0,0,0,0.08)',
    },
    // 4px base spacing scale (existing paddings already align to it).
    space: {
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 24,
    },
};

export const getStyles = (theme) => ({
    page: {
        minHeight: "100vh",
        height: "100vh",
        overflow: "hidden",
        background: theme.colors.background,
        padding: "clamp(12px, 3vw, 24px)",
        boxSizing: "border-box",
        display: "flex",
        flexDirection: "column",
        fontFamily: theme.fonts.sans,
        color: theme.colors.textPrimary,
    },
    appHeader: {
        width: "100%",
        maxWidth: "1500px",
        margin: "0 auto",
        flex: "0 0 auto",
        display: "flex",
        flexDirection: "column",
        gap: 2,
    },
    appHeaderTitle: {
        fontSize: "clamp(16px, 2.4vw, 20px)",
        fontWeight: 700,
        letterSpacing: "0.04em",
        color: theme.colors.textPrimary,
        textTransform: "uppercase",
        margin: 0,
    },
    appHeaderSubtitle: {
        fontSize: "clamp(11px, 1.6vw, 13px)",
        color: theme.colors.textSecondary,
        margin: 0,
    },
    zoomOverlay: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: "rgba(0, 0, 0, 0.85)",
        zIndex: 9999,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 20,
    },
    zoomImage: {
        maxWidth: "100%",
        maxHeight: "100%",
        objectFit: "contain",
        borderRadius: 8,
        boxShadow: "0 4px 12px rgba(0,0,0,0.5)",
    },
    viewerTools: {
        position: "absolute",
        bottom: 12,
        right: 12,
        display: "flex",
        gap: 8,
    },
    viewerToolBtn: {
        width: 36,
        height: 36,
        borderRadius: theme.radius.pill,
        background: theme.colors.cardBg,
        border: `1px solid ${theme.colors.borderMedium}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        boxShadow: theme.shadow.sm,
        color: theme.colors.textPrimary,
        padding: 0,
    },
    zoomCloseBtn: {
        position: "absolute",
        top: 20,
        right: 20,
        width: 40,
        height: 40,
        borderRadius: "50%",
        background: "rgba(255, 255, 255, 0.2)",
        border: "none",
        color: "#fff",
        fontSize: 24,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        backdropFilter: "blur(4px)",
    },
    confirmOverlay: {
        position: "fixed",
        inset: 0,
        zIndex: 10000,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 20,
        background: "rgba(0,0,0,0.32)",
        backdropFilter: "blur(3px)",
        WebkitBackdropFilter: "blur(3px)",
    },
    confirmCard: {
        width: "100%",
        maxWidth: 360,
        background: theme.colors.cardBg,
        border: `1px solid ${theme.colors.border}`,
        borderRadius: theme.radius.xl,
        padding: 24,
        display: "flex",
        flexDirection: "column",
        gap: 12,
        boxSizing: "border-box",
    },
    confirmTitle: {
        fontSize: "clamp(10px, 2vw, 11px)",
        fontWeight: 700,
        letterSpacing: "0.05em",
        color: theme.colors.textTertiary,
        textAlign: "center",
    },
    confirmMessage: {
        fontSize: 13,
        lineHeight: 1.4,
        color: theme.colors.textPrimary,
        textAlign: "center",
        padding: "4px 0",
    },
    confirmActions: {
        display: "flex",
        gap: 8,
        justifyContent: "center",
        marginTop: 4,
    },
    adminPage: {
        minHeight: "100vh",
        height: "100vh",
        overflow: "hidden",
        background: theme.colors.adminPageBg,
        padding: "clamp(12px, 3vw, 24px)",
        boxSizing: "border-box",
        fontFamily: theme.fonts.sans,
        color: theme.colors.textPrimary,
    },
    grid: {
        display: "grid",
        gridTemplateColumns: "220px 260px 260px 1fr",
        gap: "clamp(12px, 2vw, 20px)",
        alignItems: "stretch",
        flex: "1 1 auto",
        minHeight: 0,
        width: "100%",
        maxWidth: "1500px",
        margin: "0 auto",
    },
    adminGrid: {
        display: "grid",
        gridTemplateColumns: "220px 260px 1fr 1fr",
        gap: "clamp(12px, 2vw, 20px)",
        alignItems: "stretch",
        height: "calc(100vh - clamp(24px, 6vw, 48px))",
        width: "100%",
        maxWidth: "1500px",
        margin: "0 auto",
    },
    card: {
        background: theme.colors.cardBg,
        border: `1px solid ${theme.colors.border}`,
        borderRadius: theme.radius.md,
        overflow: "hidden",
        minHeight: 0,
    },
    cardBody: {
        padding: "clamp(12px, 2vw, 16px)",
        display: "flex",
        flexDirection: "column",
        height: "100%",
        minHeight: 0,
        boxSizing: "border-box",
    },

    searchWrap: { paddingBottom: 12 },
    searchPill: {
        display: "flex",
        alignItems: "center",
        gap: 10,
        background: theme.colors.inputBg,
        border: `1px solid ${theme.colors.borderMedium}`,
        borderRadius: theme.radius.md,
        padding: "8px 10px",
        boxShadow: theme.shadow.none,
        cursor: "text",
    },
    searchInput: {
        flex: 1,
        border: "none",
        outline: "none",
        fontSize: "clamp(11px, 2vw, 12px)",
        color: theme.colors.textPrimary,
        minWidth: 0,
        background: "transparent",
        padding: 0,
    },
    searchIconWrap: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        pointerEvents: "none",
    },

    holdsList: {
        overflow: "auto",
        paddingRight: 4,
        paddingBottom: 4,
        flex: 1,
        minHeight: 0,
    },
    holdRow: {
        display: "flex",
        alignItems: "center",
        gap: 6,
        padding: "2px 0", /* Reduced from "6px 0" */
        userSelect: "none",
    },

    holdRowBtn: {
        width: "100%",
        border: "1px solid transparent",
        background: "transparent",
        padding: "6px 8px",
        display: "flex",
        alignItems: "center",
        gap: 8,
        cursor: "pointer",
        textAlign: "left",
        userSelect: "none",
        outline: "none",
        boxShadow: "none",
        transition: "none",
        WebkitTapHighlightColor: "transparent",
        borderRadius: 6,
    },
    holdRowBtnActive: {
        background: "transparent",
        color: theme.colors.textPrimary,
        fontWeight: 600,
    },

    checkbox: {
        width: 14,
        height: 14,
        cursor: "pointer",
        accentColor: theme.colors.textPrimary,
    },
    holdName: {
        fontSize: "clamp(12px, 2vw, 13px)",
        color: theme.colors.textPrimary,
        lineHeight: 1.3,
    },

    footerRow: {
        display: "flex",
        flexWrap: "wrap",
        gap: 8,
        alignItems: "center",
        paddingTop: 16,
        marginTop: 16,
        borderTop: `1px solid ${theme.colors.borderLight}`,
    },
    footerBtn: {
        flex: 1,
        minWidth: 70,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },

    btnGhost: {
        border: `1px solid ${theme.colors.buttonGhostBorder}`,
        background: theme.colors.buttonGhostBg,
        borderRadius: 4,
        height: 36,
        padding: "0 12px",
        boxSizing: "border-box",
        cursor: "pointer",
        fontSize: "clamp(11px, 2vw, 12px)",
        color: theme.colors.buttonGhostText,
        transition: "none",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        textAlign: "center",
        lineHeight: 1,
    },
    btnDanger: {
        border: `1px solid ${theme.colors.borderMedium}`,
        background: theme.colors.buttonGhostBg,
        borderRadius: 4,
        height: 36,
        padding: "0 12px",
        boxSizing: "border-box",
        cursor: "pointer",
        fontSize: "clamp(11px, 2vw, 12px)",
        color: theme.colors.textSecondary,
        transition: "none",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        textAlign: "center",
        lineHeight: 1,
    },
    btnPrimary: {
        border: `1px solid ${theme.colors.buttonPrimaryBorder}`,
        background: theme.colors.buttonPrimaryBg,
        borderRadius: 4,
        height: 36,
        padding: "0 14px",
        boxSizing: "border-box",
        cursor: "pointer",
        fontSize: "clamp(11px, 2vw, 12px)",
        color: theme.colors.buttonPrimaryText,
        transition: "none",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        textAlign: "center",
        lineHeight: 1,
    },
    btnSmallGhost: {
        border: `1px solid ${theme.colors.buttonGhostBorder}`,
        background: theme.colors.buttonGhostBg,
        borderRadius: 4,
        height: 28,
        padding: "0 10px",
        boxSizing: "border-box",
        cursor: "pointer",
        fontSize: "clamp(10px, 2vw, 11px)",
        color: theme.colors.buttonGhostText,
        transition: "none",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        textAlign: "center",
        lineHeight: 1,
    },
    btnSmallGhost28: {
        border: `1px solid ${theme.colors.buttonGhostBorder}`,
        background: theme.colors.buttonGhostBg,
        borderRadius: 4,
        padding: "0 10px",
        height: 28,
        cursor: "pointer",
        fontSize: "clamp(10px, 2vw, 11px)",
        color: theme.colors.buttonGhostText,
        transition: "none",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        boxSizing: "border-box",
    },
    btnSmallPrimary: {
        border: `1px solid ${theme.colors.buttonPrimaryBorder}`,
        background: theme.colors.buttonPrimaryBg,
        borderRadius: 4,
        height: 28,
        padding: "0 10px",
        boxSizing: "border-box",
        cursor: "pointer",
        fontSize: "clamp(10px, 2vw, 11px)",
        color: theme.colors.buttonPrimaryText,
        transition: "none",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        textAlign: "center",
        lineHeight: 1,
    },

    tableBody: {
        padding: "clamp(12px, 2vw, 16px)",
        height: "100%",
        minHeight: 0,
        boxSizing: "border-box",
        display: "flex",
        flexDirection: "column",
    },
    tableHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        marginBottom: 10,
        position: "relative",
    },
    tableTitleCenter: {
        fontSize: "clamp(10px, 2vw, 11px)",
        fontWeight: 700,
        letterSpacing: "0.05em",
        color: theme.colors.textTertiary,
        textAlign: "center",
    },
    sortButton: {
        border: `1px solid ${theme.colors.buttonGhostBorder}`,
        background: theme.colors.buttonGhostBg,
        borderRadius: 4,
        width: 24,
        height: 24,
        cursor: "pointer",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 0,
        color: theme.colors.textSecondary,
        transition: "none",
        position: "absolute",
        right: 0,
    },
    table: {
        display: "flex",
        flexDirection: "column",
        gap: 4,
        overflow: "auto",
        flex: 1,
        paddingRight: 4,
        minHeight: 0,
    },
    tableRow: {
        display: "grid",
        gridTemplateColumns: "64px 1fr",
        gap: 4, /* Reduced from 10 */
        alignItems: "center",
        border: `1px solid ${theme.colors.borderLight}`,
        borderRadius: theme.radius.sm,
        padding: "3px 6px", /* Reduced from "8px 10px" */
        background: theme.colors.cardBg,
        cursor: "pointer",
        textAlign: "left",
        outline: "none",
        boxShadow: theme.shadow.none,
        transition: "none",
        WebkitTapHighlightColor: "transparent",
    },
    // UI-2a: named operator angle-row state tokens. Definitions only — these are
    // the design-system vocabulary for the row states; nothing in AngleTable
    // applies hover/active/done/muted yet (that wiring is UI-2b). Density,
    // sizing, grid, and padding from `tableRow` are intentionally unchanged.
    rowStates: {
        // current/active row: subtle accent left border + faint tint.
        active: {
            borderColor: theme.colors.borderDark,
            background: theme.colors.activeBg,
            boxShadow: `inset 3px 0 0 ${theme.colors.textPrimary}`,
        },
        // pointer hover (applied via CSS/JS in a later slice, not here).
        hover: {
            borderColor: theme.colors.borderMedium,
            background: theme.colors.hoverBg,
        },
        // completed in work mode — defined for vocabulary parity; work-mode
        // surface owns its own rendering and is not touched here.
        done: {
            borderColor: theme.colors.borderLight,
            background: theme.colors.cardBg,
            color: theme.colors.textMuted,
        },
        // muted/disabled rows.
        muted: {
            borderColor: theme.colors.borderLight,
            background: theme.colors.cardBg,
            color: theme.colors.textLight,
        },
    },
    // Meaningful "current row" style (was previously identical to default, i.e.
    // invisible). Still unused by AngleTable until UI-2b wires activeAngleId.
    tableRowActive: {
        borderColor: theme.colors.borderDark,
        background: theme.colors.activeBg,
        boxShadow: `inset 3px 0 0 ${theme.colors.textPrimary}`,
        outline: "none",
    },

    adminAngleRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 6,
        padding: "3px 0",
        cursor: "pointer",
    },
    adminAngleLabel: {
        fontWeight: 500,
        color: theme.colors.textPrimary,
        fontSize: "clamp(12px, 2vw, 13px)",
        minWidth: 50,
    },

    adminAngleInput: {
        border: `1px solid ${theme.colors.buttonGhostBorder}`,
        borderRadius: 4,
        height: 28,
        width: 70,
        padding: "0 8px",
        fontSize: "clamp(11px, 2vw, 12px)",
        outline: "none",
        background: theme.colors.inputBg,
        color: theme.colors.textPrimary,
        boxSizing: "border-box",
    },

    angleCell: {
        fontWeight: 700,
        color: theme.colors.textPrimary,
        fontSize: "clamp(13px, 2.2vw, 15px)",
        fontVariantNumeric: "tabular-nums",
        fontFeatureSettings: '"tnum" 1',
    },
    nameCell: {
        color: theme.colors.textSecondary,
        fontSize: "clamp(11px, 2vw, 12px)",
    },
    tableEmpty: { height: 8 },

    viewerWrap: { padding: "clamp(12px, 2vw, 16px)", height: "100%", boxSizing: "border-box", display: "flex", flexDirection: "column" },
    viewerEmpty: {
        width: "100%",
        height: "100%",
        border: `1px dashed ${theme.colors.viewerEmptyBorder}`,
        borderRadius: 4,
        background: theme.colors.viewerEmptyBg,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    viewerImg: {
        width: "100%",
        height: "100%",
        objectFit: "contain",
        borderRadius: 4,
        background: theme.colors.cardBg,
        flex: 1,
    },

    adminTitle: {
        fontSize: "clamp(10px, 2vw, 11px)",
        fontWeight: 600,
        letterSpacing: "0.05em",
        color: theme.colors.textTertiary,
        marginBottom: 10,
    },
    adminRow: {
        display: "flex",
        gap: 8,
        alignItems: "center",
        flexWrap: "wrap",
    },
    input: {
        border: `1px solid ${theme.colors.borderMedium}`,
        borderRadius: 4,
        height: 36,
        padding: "0 10px",
        boxSizing: "border-box",
        fontSize: "clamp(11px, 2vw, 12px)",
        outline: "none",
        background: theme.colors.inputBg,
        color: theme.colors.textPrimary,
        transition: "none",
    },
    btnX: {
        border: `1px solid ${theme.colors.buttonGhostBorder}`,
        background: theme.colors.buttonGhostBg,
        borderRadius: 4,
        width: 28,
        height: 28,
        cursor: "pointer",
        fontSize: 14,
        lineHeight: "14px",
        color: theme.colors.textSecondary,
        transition: "none",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        boxSizing: "border-box",
    },
});
